use_frameworks!

target 'QQMTASDK_Example' do
  pod 'QQMTASDK', :path => '../'

  target 'QQMTASDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
